title: Kaiwen Xia 夏凯文
description: 个人主页 / Academic homepage
url: https://ustiniankw.github.io

theme: minima
lang: zh-CN
timezone: Asia/Shanghai

header_pages:
  - index.md
  - publications.md
  - about.md

author:
  name: Kaiwen Xia
  email: XiaKaiWenjoy@163.com
  links:
    - label: GitHub
      icon: github
      url: https://github.com/ustiniankw

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
